//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ftpadmingui.rc
//
#define IDAPPLY                         2
#define ID_APPLY                        3
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDI_STARTFLAG0                  147
#define IDI_STOPFLAG                    148
#define IDB_BG_BLUE                     201
#define IDB_BG_GRAY                     202
#define IDD_BASIC_SETTING_DIALOG        203
#define IDI_SETTING                     204
#define IDD_USER_ADMIN_DLG              206
#define IDI_USER                        207
#define IDD_POLICY_ADMIN_DLG            208
#define IDI_POLICY                      209
#define IDB_BG_GREEN                    210
#define IDI_IDLEFLAG                    211
#define IDD_USER_INFORMATION            216
#define IDI_DISABLED_USER               217
#define IDI_ENABLED_USER                218
#define IDI_CREATE_USER                 219
#define IDI_REMOVE_USER                 220
#define IDI_MODIFY_USER                 221
#define IDI_FIND                        222
#define IDI_IP_REMOVE                   224
#define IDI_IP_APPEND                   225
#define IDI_APPLY                       226
#define IDI_CANCEL                      227
#define IDI_OK                          228
#define IDC_SERVICE_IP                  1001
#define IDC_BIND_IP                     1002
#define IDC_FTP_PORT                    1003
#define IDC_WEB_PORT                    1004
#define IDC_MAX_NUM_SIM_CONN            1005
#define IDC_LIST_DIR                    1006
#define IDC_MAX_NUM_SIM_CONN_CTRL       1007
#define IDC_CREATE_DIR                  1007
#define IDC_EDIT4                       1008
#define IDC_WEL_MSG                     1008
#define IDC_REMOVE_DIR                  1008
#define IDC_USER_LIST                   1009
#define IDC_CREATE_FILE                 1009
#define IDC_POLICY_REJECT               1010
#define IDC_READ_FILE                   1010
#define IDC_POLICY_PERMIT               1011
#define IDC_WRITE_FILE                  1011
#define IDC_LIST1                       1012
#define IDC_IP_LIST                     1012
#define IDC_DELETE_FILE                 1012
#define IDC_EDIT_IP                     1013
#define IDC_EXECUTE_FILE                1013
#define IDC_REMOVE_IP                   1014
#define IDC_DISABLED_USER               1014
#define IDC_EDIT1                       1015
#define IDC_NEW_IP                      1015
#define IDC_APPEND_IP                   1016
#define IDC_USERPWD                     1016
#define IDC_USERPWD_VF                  1017
#define IDC_USER_ALIAS                  1018
#define IDC_PASV_MODE                   1019
#define IDC_USER_HOME                   1019
#define IDC_BUTTON1                     1020
#define IDC_BROWSE_HOME                 1020
#define IDC_HOMEPAGE2                   1020
#define IDC_CREATE_USER                 1021
#define IDC_HOMEPAGE1                   1021
#define IDC_MODIFY_USER                 1022
#define IDC_REMOVE_USER                 1023
#define IDC_USER_WEL_MSG                1025
#define IDC_USERNAME                    1026
#define ID_SERVICE_START                32772
#define ID_BASIC_SETTING                32773
#define ID_SERVICE_STOP                 32774
#define ID_NT_SERVICE_MODE              32775
#define ID_ADMIN_ACCOUNTID              32782
#define ID_ADMIN_POLICY                 32783
#define ID_BUTTON32787                  32787
#define IDS_VIEW_FONT_STYLE             61300
#define IDS_HOST_NAME_TITLE             61301
#define IDS_HOST_IP_TITLE               61302
#define IDS_FTP_PORT_TITLE              61303
#define IDS_WEB_PORT_TITLE              61304
#define IDS_MAX_CONN_TITLE              61305
#define IDS_CURR_CONN_TITLE             61306
#define IDS_RUN_FOR_TITLE               61307
#define IDS_SERVICE_STOP_TITLE          61308
#define IDS_MSGBOX_SAVE_SETTINGS        61309
#define IDS_MSGBOX_FTP_PORT_EMPTY       61310
#define IDS_MSGBOX_WEB_PORT_EMPTY       61311
#define IDS_MSGBOX_MAX_CONN_EMPTY       61312
#define IDS_MSGBOX_SAVE_USER            61313
#define IDS_MSGBOX_USERNAME_EMPTY       61314
#define IDS_MSGBOX_HOME_DIR_EMPTY       61315
#define IDS_MSGBOX_PASSWORD_VERIFY_FAILED 61316
#define IDS_MSGBOX_PASSWORD_EMPTY       61317
#define IDS_LABEL_USER_LIST_COLUMN_ID   61318
#define IDS_LABEL_USER_LIST_COLUMN_DESC 61319
#define IDS_LABEL_USER_LIST_COLUMN_HOME_FOLDER 61320
#define IDS_MSGBOX_TITLE_ERROR          61321
#define IDS_MSGBOX_ENABLE_NT_SERVICE_TITLE 61322
#define IDS_MSGBOX_ENABLE_NT_SERVICE    61323
#define IDS_MSGBOX_DISABLE_NT_SERVICE_TITLE 61324
#define IDS_MSGBOX_DISABLE_NT_SERVICE   61325
#define IDS_MSGBOX_SAVE_BASIC_SETTING_TITLE 61326
#define IDS_MSGBOX_SAVE_BASIC_SETTING   61327
#define IDS_MSGBOX_SAVE_POLICY_TITLE    61328
#define IDS_MSGBOX_SAVE_POLICY          61329
#define IDS_MSGBOX_RESTART_SERVICE_TITLE 61330
#define IDS_MSGBOX_LOAD_CONFIG_CONFIRM  61331
#define IDS_MSGBOX_START_SERVICE_TITLE  61332
#define IDS_MSGBOX_START_SERVICE_FAILED 61333
#define IDS_MSGBOX_STOP_SERVICE_TITLE   61334
#define IDS_MSGBOX_STOP_SERVICE_FAILED  61335
#define IDS_MSGBOX_INATLL_SERVICE_TITLE 61336
#define IDS_MSGBOX_INATLL_SERVICE_FAILED 61337
#define IDS_MSGBOX_REGISTE_SERVICE_FAILED 61338
#define IDS_MSGBOX_REGISTE_SERVICE_OK   61339
#define IDS_MSGBOX_REGISTE_SERVICE_TITLE 61340
#define IDS_MSGBOX_UNREGISTER_SERVICE_TITLE 61341
#define IDS_MSGBOX_UNREGISTER_SERVICE_FAILED 61342
#define IDS_MSGBOX_UNREGISTER_SERVICE_OK 61343
#define IDS_MSGBOX_IP_EXIST             61344
#define IDS_MSGBOX_SEL_RECORD_ALERT     61345
#define IDS_MSGBOX_USER_EXIST           61346
#define IDS_MSGBOX_SEL_USER_MODIFY      61347
#define IDS_MSGBOX_SEL_USER_REMOVE      61348
#define IDS_MSGBOX_REMOVE_USER_CONFIRM  61349
#define IDS_MSGBOX_REMOVE_USER_TITLE    61350
#define IDS_MSGBOX_GET_FOLDER_FAILED    61351
#define IDS_WEB_CHANGE_PWD              61352
#define IDS_WEB_NEW_PWD                 61353
#define IDS_WEB_VERIFY_PWD              61354
#define IDS_WEB_BTN_VALUE_UPDATE        61355
#define IDS_WEB_PASSWORD_ALERT_EMPTY    61356
#define IDS_WEB_PASSWORD_ALERT_VERIFY   61357
#define IDS_WEB_LIST_FILES              61358
#define IDS_WEB_PASSWORD_UPDATE_SUCCESFULLY 61359

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        240
#define _APS_NEXT_COMMAND_VALUE         32788
#define _APS_NEXT_CONTROL_VALUE         1028
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
